repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: '^.docker/'
    -   id: check-added-large-files
        args:
        - --maxkb=512
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
        exclude: '^.docker/'
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: '^.docker/'
    -   id: pretty-format-json
        exclude: '^.docker/'
        args:
        - --autofix
    -   id: requirements-txt-fixer
