repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: '^.docker/'
    -   id: check-added-large-files
        args:
        - --maxkb=512
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
        exclude: '^.docker/'
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: '^.docker/'
    -   id: pretty-format-json
        exclude: '^.docker/'
        args:
        - --autofix
    -   id: requirements-txt-fixer
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22
  hooks:
    - id: shellcheck
      exclude: '.*\.sh\.j2'
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.35.0
  hooks:
    - id: markdownlint-fix
