#!/data/data/com.termux/files/usr/bin/env bash
# Enable bash's unofficial strict mode
GITROOT=$(git rev-parse --show-toplevel)
. ${GITROOT}/lib/strict-mode
strictMode
# Enabling utils
. ${GITROOT}/lib/utils
. ${GITROOT}/scripts/base

function download_and_install_deb() {
  local DEB_URL="${1}"
  local DEB_NAME="${2}"
  local DEB_FILE_NAME="${DEB_NAME}.deb"

  if ! grep -q "${DEB_NAME}" <(apt list --installed 2> /dev/null); then
    msg_info "Will download and install ${DEB_NAME}"
    curl -Lv "${DEB_URL}" -o "${DEB_FILE_NAME}"
    DEBIAN_FRONTEND='noninteractive' apt install -y "./${DEB_FILE_NAME}"
    rm "${DEB_FILE_NAME}"
  else
    msg_info "${DEB_NAME} is installed already"
  fi
}

declare -A DEB_PACKAGES=(
  ['python']='https://github.com/Termux-pod/termux-pod/raw/main/aarch64/python/python-3.9.7/python_3.9.7_aarch64.deb'
)

for KEY in "${!DEB_PACKAGES[@]}"; do
  download_and_install_deb "${DEB_PACKAGES[${KEY}]}" "${KEY}"
done
